# Generated by Django 5.0.1 on 2024-09-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
