# Generated by Django 5.0.1 on 2024-09-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_name_alter_message_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-last_message_time'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
