# Generated by Django 5.0.1 on 2024-09-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'chit_chat_user', 'verbose_name_plural': 'Chit Chat Users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='chit_chat_user',
        ),
    ]
