# Generated by Django 5.0.1 on 2024-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
